export const FETCH_CONVERSATIONS = 'inbox.FETCH_CONVERSATIONS';
export const RECEIVED_CONVERSATIONS = 'inbox.RECEIVED_CONVERSATIONS';
export const RECEIVED_CONVERSATION = 'inbox.RECEIVED_CONVERSATION';
export const LOADING_ERROR = 'inbox.LOADING_ERROR';
